sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
  
before_script:
  - mkdir build
  - cd build
  - cmake ../src/hello
  - cd ..

script:
  - cd build
  - make
  - ./hello
