sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9
  
before_install:
  - pip install --user cpp-coveralls

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${CXX_COMPILER} --version
  - CXX=${CXX_COMPILER} cmake ../src/hello
  - cd ..

script:
  - cd build
  - make
  - ./hello
  - cd ..

after_success:
  - coveralls -r . -b build --gcov gcov-4.9 --gcov-options '\-lp'