sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MY_CMAKE=CXX=g++-4.9 ${TRAVIS_BUILD_DIR}/cmake/bin/cmake
        - MY_CMAKE_GEN=UNIX makefiles

before_install:
  - pip install --user cpp-coveralls

install:
  - |
    CMAKE_URL="http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake

before_script:
  - mkdir build
  - cd build
  - ${MY_CMAKE} --version
  - echo ${MY_CMAKE_GEN}
  - ${MY_CMAKE} ../src/hello
  - cd ..

script:
  - cd build
  - make
  - ./hello
  - cd ..

after_success:
  - coveralls -r . -b build --gcov gcov-4.9 --gcov-options '\-lp'