sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX_COMPILER=g++-4.9
  
before_install:
  - pip install --user cpp-coveralls

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${CXX_COMPILER} --version
  - CXX=${CXX_COMPILER} cmake ../src/hello
  - cd ..

script:
  - cd build
  - make
  - ./hello
  - cd ..

after_success:
  - coveralls -r . -b build --gcov gcov-4.9 --gcov-options '\-lp'