sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - qt551
          packages:
            - g++-4.9
            - qt55base
      env:
        - MY_CMAKE=${TRAVIS_BUILD_DIR}/cmake/bin/cmake
        - MY_CMAKE_GEN='Unix Makefiles'
        - CXX_COMPILER=g++-4.9
        - CC_COMPILER=gcc-4.9

before_install:
  - pip install --user cpp-coveralls

install:
  - |
    CMAKE_URL="http://cmake.org/files/v3.4/cmake-3.4.3-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake

before_script:
  - mkdir build
  - cd build
  - ${CXX_COMPILER} --version
  - ${CC_COMPILER} --version
  - ${MY_CMAKE} --version
  - CXX=${CXX_COMPILER} CC=${CC_COMPILER} ${MY_CMAKE} ../src/hello
  - cd ..

script:
  - cd build
  - make
  - ./hello
  - cd ..

after_success:
  - coveralls -r . -b build --gcov gcov-4.9 --gcov-options '\-lp'
